REM   Script: 0417_am_sqlpr
REM   04/17 오전 sql연습


CREATE TABLE player ( 
    player_id NUMBER GENERATED BY DEFAULT AS IDENTITY, 
    position VARCHAR2(50), 
    height NUMBER 
);

INSERT INTO player (position, height) VALUES ('Forward', 180);

INSERT INTO player (position, height) VALUES ('Forward', 185);

INSERT INTO player (position, height) VALUES ('Forward', 175);

INSERT INTO player (position, height) VALUES ('Midfielder', 170);

INSERT INTO player (position, height) VALUES ('Midfielder', 175);

INSERT INTO player (position, height) VALUES ('Defender', 190);

INSERT INTO player (position, height) VALUES ('Defender', 195);

INSERT INTO player (position, height) VALUES ('Defender', 180);

INSERT INTO player (position, height) VALUES ('Goalkeeper', 195);

INSERT INTO player (position, height) VALUES ('Goalkeeper', 198);

SELCET * FROM player;


SELCET * FROM player;


CREATE TABLE player ( 
    player_id NUMBER GENERATED BY DEFAULT AS IDENTITY, 
    position VARCHAR2(50), 
    height NUMBER 
);

INSERT INTO player (position, height) VALUES ('Forward', 180);

INSERT INTO player (position, height) VALUES ('Forward', 185);

INSERT INTO player (position, height) VALUES ('Forward', 175);

INSERT INTO player (position, height) VALUES ('Midfielder', 170);

INSERT INTO player (position, height) VALUES ('Midfielder', 175);

INSERT INTO player (position, height) VALUES ('Defender', 190);

INSERT INTO player (position, height) VALUES ('Defender', 195);

INSERT INTO player (position, height) VALUES ('Defender', 180);

INSERT INTO player (position, height) VALUES ('Goalkeeper', 195);

INSERT INTO player (position, height) VALUES ('Goalkeeper', 198);

SELCET * FROM player; 


drop table player;

CREATE TABLE player ( 
    player_id NUMBER GENERATED BY DEFAULT AS IDENTITY, 
    position VARCHAR2(50), 
    height NUMBER 
);

INSERT INTO player (position, height) VALUES ('Forward', 180);

INSERT INTO player (position, height) VALUES ('Forward', 185);

INSERT INTO player (position, height) VALUES ('Forward', 175);

INSERT INTO player (position, height) VALUES ('Midfielder', 170);

INSERT INTO player (position, height) VALUES ('Midfielder', 175);

INSERT INTO player (position, height) VALUES ('Defender', 190);

INSERT INTO player (position, height) VALUES ('Defender', 195);

INSERT INTO player (position, height) VALUES ('Defender', 180);

INSERT INTO player (position, height) VALUES ('Goalkeeper', 195);

INSERT INTO player (position, height) VALUES ('Goalkeeper', 198);

SELCET * FROM player;


SELECT * FROM player;

SELECT position '포지션', AVG(height) '평균 키' 
FROM player 
GROUP BY position '포지션';

SELECT 
	position AS "포지션", 
	COUNT(*) AS "인원수", 
	COUNT(height) AS "키 대상", 
	MAX(height) AS "최대 키", 
	MIN(height) AS "최소 키", 
	ROUND(AVG(height), 2) AS "평균 키" 
FROM player 
GROUP BY position;

DROP TABLE pokemon;

CREATE TABLE pokemon ( 
  pm_id NUMBER PRIMARY KEY NOT NULL, 
  name VARCHAR2(50) NOT NULL, 
  attr VARCHAR2(50) DEFAULT 'normal', 
	weight NUMBER 
);

INSERT INTO pokemon VALUES (1, 'Bulbasaur', 'grass', 30);

INSERT INTO pokemon VALUES (2, 'Ivysaur', 'grass', 50);

INSERT INTO pokemon VALUES (3, 'Venusaur', 'grass', 150);

INSERT INTO pokemon VALUES (4, 'Charmander', 'Fire', 80);

INSERT INTO pokemon VALUES (5, 'Charmeleon', 'Fire', 200);

INSERT INTO pokemon VALUES (25, 'Pikachu', 'Electric', 15);

INSERT INTO pokemon (pm_id, name) VALUES (86, 'Seel');

SELECT * FROM pokemon;

SELECT  
	attr, 
	AVG(weight) 
FROM pokemon 
GROUP BY attr;

DROP TABLE pokemon;

CREATE TABLE pokemon ( 
  pm_id NUMBER PRIMARY KEY NOT NULL, 
  name VARCHAR2(20) NOT NULL, 
  attr VARCHAR2(20), 
	weight VARCHAR2(20) 
);

INSERT INTO pokemon VALUES (1, 'Bulbasaur', 'Grass', '30');

INSERT INTO pokemon VALUES (4, 'Charmander', 'Fire', '80');

INSERT INTO pokemon VALUES (25, 'Pikachu', 'Electric', '15');

INSERT INTO pokemon (pm_id, name) VALUES (54, 'Psyduck');

INSERT INTO pokemon (pm_id, name, attr) VALUES (76, 'Golem', 'Rock');

INSERT INTO pokemon (pm_id, name, weight) VALUES (86, 'Seel', '85');

SELECT  
	attr,  
	AVG(weight) 
FROM pokemon 
GROUP BY attr 
HAVING attr IS NOT NULL;

SELECT  
	attr,  
	AVG(weight) 
FROM pokemon 
GROUP BY attr 
HAVING attr IS NOT NULL;

SELECT  
	attr,  
	AVG(weight) 
FROM pokemon 
GROUP BY attr 
-- HAVING attr IS NOT NULL;

drop table player;

CREATE TABLE player ( 
    player_id NUMBER GENERATED BY DEFAULT AS IDENTITY, 
    position VARCHAR2(50), 
    height NUMBER 
);

INSERT INTO player (position, height) VALUES ('Forward', 180);

INSERT INTO player (position, height) VALUES ('Forward', 185);

INSERT INTO player (position, height) VALUES ('Forward', 175);

INSERT INTO player (position, height) VALUES ('Midfielder', 170);

INSERT INTO player (position, height) VALUES ('Midfielder', 175);

INSERT INTO player (position, height) VALUES ('Defender', 190);

INSERT INTO player (position, height) VALUES ('Defender', 195);

INSERT INTO player (position, height) VALUES ('Defender', 180);

INSERT INTO player (position, height) VALUES ('Goalkeeper', 195);

INSERT INTO player (position, height) VALUES ('Goalkeeper', 198);

SELECT * FROM player;

SELECT position '포지션', AVG(height) '평균 키' 
from player;

SELECT position '포지션', AVG(height) '평균 키' 
FROM player 
GROUP BY position '포지션';

SELECT 
	position AS "포지션", 
	COUNT(*) AS "인원수", 
	COUNT(height) AS "키 대상", 
	MAX(height) AS "최대 키", 
	MIN(height) AS "최소 키", 
	ROUND(AVG(height), 2) AS "평균 키" 
FROM player 
GROUP BY position;

CREATE TABLE pokemon ( 
  pm_id NUMBER PRIMARY KEY NOT NULL, 
  name VARCHAR2(50) NOT NULL, 
  attr VARCHAR2(50) DEFAULT 'normal', 
	weight NUMBER 
);

INSERT INTO pokemon VALUES (1, 'Bulbasaur', 'grass', 30);

INSERT INTO pokemon VALUES (2, 'Ivysaur', 'grass', 50);

INSERT INTO pokemon VALUES (3, 'Venusaur', 'grass', 150);

INSERT INTO pokemon VALUES (4, 'Charmander', 'Fire', 80);

INSERT INTO pokemon VALUES (5, 'Charmeleon', 'Fire', 200);

INSERT INTO pokemon VALUES (25, 'Pikachu', 'Electric', 15);

INSERT INTO pokemon (pm_id, name) VALUES (86, 'Seel');

SELECT * FROM pokemon;

SELECT  
	attr, 
	AVG(weight) 
FROM pokemon 
GROUP BY attr;

DROP TABLE pokemon;

CREATE TABLE pokemon ( 
  pm_id NUMBER PRIMARY KEY NOT NULL, 
  name VARCHAR2(20) NOT NULL, 
  attr VARCHAR2(20), 
	weight VARCHAR2(20) 
);

INSERT INTO pokemon VALUES (1, 'Bulbasaur', 'Grass', '30');

INSERT INTO pokemon VALUES (4, 'Charmander', 'Fire', '80');

INSERT INTO pokemon VALUES (25, 'Pikachu', 'Electric', '15');

INSERT INTO pokemon (pm_id, name) VALUES (54, 'Psyduck');

INSERT INTO pokemon (pm_id, name, attr) VALUES (76, 'Golem', 'Rock');

INSERT INTO pokemon (pm_id, name, weight) VALUES (86, 'Seel', '85');

SELECT  
	attr,  
	AVG(weight) 
FROM pokemon 
GROUP BY attr 
HAVING attr IS NOT NULL;

SELECT  
	attr,  
	AVG(weight) 
FROM pokemon 
GROUP BY attr 
-- HAVING attr IS NOT NULL;

CREATE TABLE student ( 
  id NUMBER, 
  class NUMBER, 
  score NUMBER 
);

INSERT INTO student VALUES (1, 1, 10);

INSERT INTO student VALUES (2, 1, 10);

INSERT INTO student VALUES (3, 1, 10);

INSERT INTO student VALUES (4, 1, 10);

INSERT INTO student VALUES (5, 1, 10);

INSERT INTO student VALUES (6, 1, 10);

INSERT INTO student VALUES (7, 1, 10);

INSERT INTO student VALUES (8, 1, 10);

INSERT INTO student VALUES (9, 1, null);

INSERT INTO student VALUES (10, 1, null);

SELECT  
	class,  
	AVG(score),  
	COUNT(score),  
	COUNT(*) 
FROM student 
GROUP BY class;

DROP TABLE pokemon;

CREATE TABLE pokemon ( 
  pm_id NUMBER PRIMARY KEY NOT NULL, 
  name VARCHAR2(20) NOT NULL, 
  attr VARCHAR2(20) DEFAULT 'normal', 
	height NUMBER 
);

INSERT INTO pokemon VALUES (1, 'Bulbasaur', 'grass', 50);

INSERT INTO pokemon VALUES (2, 'Ivysaur', 'grass', 90);

INSERT INTO pokemon VALUES (3, 'Venusaur', 'grass', 250);

INSERT INTO pokemon VALUES (4, 'Charmander', 'Fire', 80);

INSERT INTO pokemon VALUES (5, 'Charmeleon', 'Fire', 120);

INSERT INTO pokemon VALUES (25, 'Pikachu', 'Electric', 50);

SELECT  
	name,  
	height  
FROM pokemon 
ORDER BY height DESC, name ASC;

CREATE TABLE emp ( 
 
    empno NUMBER, 
 
    ename VARCHAR2(50), 
 
    job VARCHAR2(50), 
 
    mgr NUMBER, 
 
    hiredate DATE, 
 
    sal NUMBER, 
 
    deptno NUMBER 
 
);

INSERT INTO emp (empno, ename, job, mgr, hiredate, sal, deptno) VALUES (7839, 'KING', 'PRESIDENT', NULL, TO_DATE('1981-11-17', 'YYYY-MM-DD'), 5000, 10);

INSERT INTO emp (empno, ename, job, mgr, hiredate, sal, deptno) VALUES (7566, 'JONES', 'MANAGER', 7839, TO_DATE('1981-04-02', 'YYYY-MM-DD'), 2975, 20);

INSERT INTO emp (empno, ename, job, mgr, hiredate, sal, deptno) VALUES (7698, 'BLAKE', 'MANAGER', 7839, TO_DATE('1981-05-01', 'YYYY-MM-DD'), 2850, 30);

INSERT INTO emp (empno, ename, job, mgr, hiredate, sal, deptno) VALUES (7782, 'CLARK', 'MANAGER', 7839, TO_DATE('1981-06-09', 'YYYY-MM-DD'), 2450, 10);

INSERT INTO emp (empno, ename, job, mgr, hiredate, sal, deptno) VALUES (7902, 'FORD', 'ANALYST', 7566, TO_DATE('1981-12-03', 'YYYY-MM-DD'), 3000, 20);

INSERT INTO emp (empno, ename, job, mgr, hiredate, sal, deptno) VALUES (7369, 'SMITH', 'CLERK', 7902, TO_DATE('1980-12-17', 'YYYY-MM-DD'), 800, 20);

INSERT INTO emp (empno, ename, job, mgr, hiredate, sal, deptno) VALUES (7521, 'WARD', 'SALESMAN', 7698, TO_DATE('1981-02-22', 'YYYY-MM-DD'), 1250, 30);

INSERT INTO emp (empno, ename, job, mgr, hiredate, sal, deptno) VALUES (7654, 'MARTIN', 'SALESMAN', 7698, TO_DATE('1981-09-28', 'YYYY-MM-DD'), 1250, 30);

INSERT INTO emp (empno, ename, job, mgr, hiredate, sal, deptno) VALUES (7844, 'TURNER', 'SALESMAN', 7698, TO_DATE('1981-09-08', 'YYYY-MM-DD'), 1500, 30);

INSERT INTO emp (empno, ename, job, mgr, hiredate, sal, deptno) VALUES (7900, 'JAMES', 'CLERK', 7698, TO_DATE('1981-12-03', 'YYYY-MM-DD'), 950, 30);

SELECT job, sal FROM emp GROUP BY job HAVING COUNT(*) > 0 ORDER BY sal;

SELECT job FROM emp GROUP BY job HAVING COUNT(*) > 0 ORDER BY sal;

SELECT job FROM emp GROUP BY job HAVING COUNT(*) > 0  
ORDER BY MAX(empno), MAX(mgr), SUM(sal), COUNT(deptno), MAX(hiredate);

SELECT ename, sal FROM emp WHERE ROWNUM < 4 ORDER BY sal DESC;

DROP TABLE pokemon;

CREATE TABLE pokemon ( 
  pm_id NUMBER PRIMARY KEY NOT NULL, 
  name VARCHAR2(20) NOT NULL, 
  attr VARCHAR2(20) DEFAULT 'normal', 
	height NUMBER 
);

INSERT INTO pokemon VALUES (1, 'Bulbasaur', 'grass', 50);

INSERT INTO pokemon VALUES (2, 'Ivysaur', 'grass', 90);

INSERT INTO pokemon VALUES (3, 'Venusaur', 'grass', 250);

INSERT INTO pokemon VALUES (4, 'Charmander', 'Fire', 80);

INSERT INTO pokemon VALUES (5, 'Charmeleon', 'Fire', 120);

INSERT INTO pokemon VALUES (25, 'Pikachu', 'Electric', 50);

INSERT INTO pokemon VALUES (86, 'Seel', 'Ice', 80);

SELECT  
    name,  
    attr, 
    height  
FROM pokemon WHERE ROWNUM < 4 ORDER BY height, name;

